// Generated by LiveScript 1.3.1
var data, hot, count, update, onchange;
data = [["", "Judge John", "Judge Joe", "Judge Jacob", "Judge Judy"], ["Sakura", 90, 60, 80, 70], ["Sasuke", 80, 50, 70, 60], ["Naruto", 70, 40, 60, 50], ["Kakasi", 60, '', 50, 40], ["Itachi", 50, 20, '', 30]];
hot = new Handsontable(document.querySelector('#grid .inner'), {
  data: data,
  rowHeaders: true,
  colHeaders: true,
  filters: true,
  dropdownMenu: true,
  afterChange: onchange,
  rowHeights: 35,
  colWidths: 100
});
count = {
  row: hot.countRows(),
  col: hot.countCols()
};
hot.alter("insert_col", count.col);
hot.updateSettings({
  cells: function(r, c){
    if (c === count.col) {
      return {
        readOnly: true
      };
    } else {
      return {};
    }
  }
});
update = function(){
  var votes, ret, i$, to$, i, cand, results$ = [];
  votes = JSON.parse(JSON.stringify(data));
  votes.map(function(it){
    return it.splice(it.length - 1, 1);
  });
  ret = fromArray(votes, {});
  hot.setDataAtCell(0, count.col, 'Rank');
  for (i$ = 0, to$ = ret.length; i$ < to$; ++i$) {
    i = i$;
    cand = ret[i];
    results$.push(hot.setDataAtCell(cand.idx + 1, count.col, cand.rank));
  }
  return results$;
};
update();
onchange = function(){
  return update();
};